# modulario:template
"""watch.py — health checks for core

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))


# ── Import checks ──────────────────────────────
# Verify key modules in this folder can be imported without error.
def check_imports():
    pass  # e.g. from core import main_module


# ── Public API checks ─────────────────────────
# Verify expected functions/classes exist and are callable.
def check_public_api():
    pass  # e.g. assert callable(main_module.some_function)


# ── Invariant checks ──────────────────────────
# Verify structural rules that must remain true for this folder.
def check_invariants():
    pass  # e.g. assert config file exists, assert no forbidden patterns


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
