"""`mod watch ...` — per-folder watch.py scripts."""
import argparse
import os
import subprocess
import sys
from pathlib import Path

from cli_common import (
    MODULARIO_DIR,
    active_target_dir,
    filter_walk_dirs,
    load_skip_dirs,
    resolve_target_folder,
)

WATCH_MARKER = '# modulario:template'


def _template(folder_name, parents):
    return f'''{WATCH_MARKER}
"""watch.py — health checks for {folder_name}

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '{parents}'))


# ── Import checks ──────────────────────────────
# Verify key modules in this folder can be imported without error.
def check_imports():
    pass  # e.g. from {folder_name} import main_module


# ── Public API checks ─────────────────────────
# Verify expected functions/classes exist and are callable.
def check_public_api():
    pass  # e.g. assert callable(main_module.some_function)


# ── Invariant checks ──────────────────────────
# Verify structural rules that must remain true for this folder.
def check_invariants():
    pass  # e.g. assert config file exists, assert no forbidden patterns


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {{fn.__name__}}: {{e}}", file=sys.stderr)
            sys.exit(1)
'''


def _cmd_run(target):
    watch_runner = Path(MODULARIO_DIR) / 'scripts' / 'modulario-watch-runner.py'
    result = subprocess.run(
        [sys.executable, str(watch_runner),
         '--target', target, '--changed-file', '', '--print-plain', '--show-summary'],
        capture_output=True, text=True,
    )
    if result.stdout:
        print(result.stdout.rstrip())
    if result.stderr:
        print(result.stderr.rstrip(), file=sys.stderr)
    if result.returncode:
        raise SystemExit(result.returncode)


def _cmd_init(target, folder_arg):
    _, folder = resolve_target_folder(folder_arg)
    folder_name = folder.rstrip('/').split('/')[-1] if folder != '/' else os.path.basename(target)
    abs_watch = os.path.join(target, folder.rstrip('/'), 'watch.py') if folder != '/' else os.path.join(target, 'watch.py')
    if os.path.exists(abs_watch):
        print(f"File already exists: {folder}watch.py")
        sys.exit(1)
    depth = len(folder.rstrip('/').split('/')) if folder != '/' else 0
    parents = '/'.join(['..'] * depth) if depth else '.'
    os.makedirs(os.path.dirname(abs_watch), exist_ok=True)
    with open(abs_watch, 'w') as f:
        f.write(_template(folder_name, parents))
    print(f"Created {folder}watch.py — fill in the check stubs.")


def _cmd_status(target):
    unfilled, filled, disabled = [], [], []
    skip_dirs = load_skip_dirs()
    for root, dirs, _filenames in os.walk(target):
        dirs[:] = filter_walk_dirs(root, dirs, target, skip_dirs)
        watch = os.path.join(root, 'watch.py')
        rel = os.path.relpath(root, target)
        rel = '/' if rel == '.' else rel + '/'
        if os.path.exists(os.path.join(root, '.watch.dismissed')):
            continue
        if os.path.exists(os.path.join(root, '.watch.disabled')):
            disabled.append(rel)
            continue
        if not os.path.exists(watch):
            unfilled.append((rel, 'missing'))
        else:
            try:
                with open(watch, 'r') as f:
                    first_line = f.readline()
                if WATCH_MARKER in first_line:
                    unfilled.append((rel, 'unfilled'))
                else:
                    filled.append(rel)
            except OSError:
                pass
    if filled:
        print(f"Enabled ({len(filled)}):")
        for folder in sorted(filled):
            print(f"  {folder}")
    if disabled:
        print(f"Disabled ({len(disabled)}):")
        for folder in sorted(disabled):
            print(f"  {folder}")
    if unfilled:
        print(f"Unfilled ({len(unfilled)}):")
        for folder, st in sorted(unfilled):
            print(f"  {folder:<40} {st}")
    if not filled and not disabled and not unfilled:
        print("No folders found.")


def _cmd_enable(target, folder_arg):
    _, folder = resolve_target_folder(folder_arg)
    abs_folder = os.path.join(target, folder.rstrip('/')) if folder != '/' else target
    marker = os.path.join(abs_folder, '.watch.disabled')
    if os.path.exists(marker):
        os.remove(marker)
        print(f"Enabled watch for '{folder}'.")
    else:
        print(f"Watch for '{folder}' is already enabled.")


def _cmd_disable(target, folder_arg):
    _, folder = resolve_target_folder(folder_arg)
    abs_folder = os.path.join(target, folder.rstrip('/')) if folder != '/' else target
    marker = os.path.join(abs_folder, '.watch.disabled')
    if os.path.exists(marker):
        print(f"Watch for '{folder}' is already disabled.")
    else:
        with open(marker, 'w') as f:
            f.write('')
        print(f"Disabled watch for '{folder}'.")


def _cmd_dismiss(target, folder_arg):
    _, folder = resolve_target_folder(folder_arg)
    abs_folder = os.path.join(target, folder.rstrip('/')) if folder != '/' else target
    marker = os.path.join(abs_folder, '.watch.dismissed')
    if os.path.exists(marker):
        print(f"Already dismissed: {folder}")
        return
    watch_file = os.path.join(abs_folder, 'watch.py')
    if os.path.exists(watch_file):
        with open(watch_file, 'r') as f:
            first_line = f.readline()
        if WATCH_MARKER in first_line:
            os.remove(watch_file)
    with open(marker, 'w') as f:
        f.write('')
    print(f"Dismissed watch nag for '{folder}'.")


def cmd_watch(argv):
    p = argparse.ArgumentParser(prog='mod watch', add_help=True)
    sub = p.add_subparsers(dest='watch_cmd', required=True)

    sub.add_parser('run', help='Run all enabled watch.py scripts')

    p_init = sub.add_parser('init', help='Create a watch.py template in a folder')
    p_init.add_argument('folder')

    sub.add_parser('status', help='Show watch.py status for all folders')

    p_enable = sub.add_parser('enable', help='Enable a watch for a folder')
    p_enable.add_argument('folder')

    p_disable = sub.add_parser('disable', help='Disable a watch for a folder')
    p_disable.add_argument('folder')

    p_dismiss = sub.add_parser('dismiss', help='Dismiss watch nag (folder has no source files)')
    p_dismiss.add_argument('folder')

    args = p.parse_args(argv)
    target = active_target_dir()

    dispatch = {
        'run':     lambda: _cmd_run(target),
        'init':    lambda: _cmd_init(target, args.folder),
        'status':  lambda: _cmd_status(target),
        'enable':  lambda: _cmd_enable(target, args.folder),
        'disable': lambda: _cmd_disable(target, args.folder),
        'dismiss': lambda: _cmd_dismiss(target, args.folder),
    }
    dispatch[args.watch_cmd]()
